site_name: VATSIM Siberia Documentation
site_url: https://vatsib.github.io/docs/


repo_url: https://github.com/VATSIB/docs
repo_name: VATSIB/docs

theme:
  language: ru
  name: material
  palette: 
    scheme: slate
    primary: indigo
    accent: pink
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top

nav:
  - Главная: index.md

  - Программное Обеспечение:
      - EuroScope:
          - Установка EuroScope:   software/euroscope.md
          - Сектор-файл: software/sector-file.md

      - TrackAudio:
          - Обзор: software/trackaudio.md
      - Lists:
          - Обзор: software/lists.md
   
extra_css:
  - assets/style/extra.css

extra_javascript:
  - assets/scripts/links.js

plugins:
  - search:
      lang: ru
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details 
  - pymdownx.superfences
  - attr_list


extra:
  social:
    - icon: simple/github
      link: https://github.com/VATSIB
    - icon: simple/discord
      link: https://community.vatsim.net/

copyright: Copyright © 2026 VATSIM Siberia.