site_name: VATSIM Siberia Documentation
site_url: https://vatsib.github.io/docs/

theme:
  language: ru
  name: material
  palette: 
    scheme: slate
    primary: indigo
    accent: pink
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top

nav:
  - Главная: index.md
  - Програмное Обеспечение:
      - Установка EuroScope: software/euroscope.md
      - VATSIM Server: software/vatsim-server.md

extra_css:
  - assets/style/extra.css

plugins:
 ## - offline
  - search:
      lang: ru

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details 


extra:
  social:
    - icon: simple/github
      link: https://github.com/VATSIB
    - icon: simple/discord
      link: https://community.vatsim.net/

copyright: Copyright © 2026 VATSIM Siberia.